# Generated by Django 5.0 on 2023-12-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_customers', to='main.product')),
            ],
        ),
    ]
